// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Project struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type ProjectUser struct {
	ProjectID string
	UserID    string
	Role      string
}

type Sandbox struct {
	ID        string
	ProjectID string
	UserID    string
	CreatedAt time.Time
	StoppedAt sql.NullTime
	Version   int32
	Name      string
}

type User struct {
	ID        string
	Email     string
	Name      string
	CreatedAt time.Time
	OauthSub  string
}
