// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Plan struct {
	ID                  string
	Name                string
	MaxProjects         int32
	MaxRunningSandboxes int32
	CreatedAt           time.Time
}

type Project struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type ProjectUser struct {
	ProjectID string
	UserID    string
	Role      string
}

type Sandbox struct {
	ID        string
	ProjectID string
	UserID    string
	Name      string
	CreatedAt time.Time
	StoppedAt sql.NullTime
}

type User struct {
	ID        string
	Email     string
	Name      string
	PlanID    string
	CreatedAt time.Time
}
