// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
)

const countProjectsOwnedByUser = `-- name: CountProjectsOwnedByUser :one
SELECT COUNT(*) FROM project_users WHERE user_id = $1 AND role = 'owner'
`

func (q *Queries) CountProjectsOwnedByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsOwnedByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserPlan = `-- name: GetUserPlan :one
SELECT p.id, p.name, p.max_projects, p.max_running_sandboxes, p.created_at
FROM users u
JOIN plans p ON p.id = u.plan_id
WHERE u.id = $1
`

func (q *Queries) GetUserPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getUserPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxProjects,
		&i.MaxRunningSandboxes,
		&i.CreatedAt,
	)
	return i, err
}
