// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_users (project_id, user_id, role) VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID string
	UserID    string
	Role      string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*) FROM projects p
JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, created_at FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectMembership = `-- name: GetProjectMembership :one
SELECT pu.role FROM projects p
LEFT JOIN project_users pu ON pu.project_id = p.id AND pu.user_id = $2
WHERE p.id = $1
`

type GetProjectMembershipParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getProjectMembership, arg.ID, arg.UserID)
	var role sql.NullString
	err := row.Scan(&role)
	return role, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.name, p.created_at FROM projects p
JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByUserParams struct {
	UserID string
	Limit  int32
	Offset int32
}

func (q *Queries) ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
