// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const countProjectsByOwner = `-- name: CountProjectsByOwner :one
SELECT COUNT(*) FROM (
    SELECT 1 FROM projects
    WHERE owner_id = $1
    LIMIT $2
) owned
`

type CountProjectsByOwnerParams struct {
	OwnerID string
	Limit   int32
}

// The LIMIT caps the scan at the plan cap (see CountRunningSandboxesByUser).
func (q *Queries) CountProjectsByOwner(ctx context.Context, arg CountProjectsByOwnerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByOwner, arg.OwnerID, arg.Limit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*) FROM projects p
JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, name) VALUES ($1, $2) RETURNING id, owner_id, name, created_at
`

type CreateProjectParams struct {
	OwnerID string
	Name    string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.OwnerID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectMember = `-- name: CreateProjectMember :exec
INSERT INTO project_users (project_id, user_id) VALUES ($1, $2)
`

type CreateProjectMemberParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, createProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, name, created_at FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMembership = `-- name: GetProjectMembership :one
SELECT pu.user_id AS member_user_id,
       (p.owner_id = $1)::bool AS is_owner
FROM projects p
LEFT JOIN project_users pu ON pu.project_id = p.id AND pu.user_id = $1
WHERE p.id = $2
`

type GetProjectMembershipParams struct {
	CallerID  string
	ProjectID string
}

type GetProjectMembershipRow struct {
	MemberUserID sql.NullString
	IsOwner      bool
}

// One round-trip answers both authorization questions: does the project
// exist, and what is the caller's derived role (ownership is an attribute
// of the project; project_users is the access list). member_user_id is
// NULL when the caller is not a member.
func (q *Queries) GetProjectMembership(ctx context.Context, arg GetProjectMembershipParams) (GetProjectMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectMembership, arg.CallerID, arg.ProjectID)
	var i GetProjectMembershipRow
	err := row.Scan(&i.MemberUserID, &i.IsOwner)
	return i, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.owner_id, p.name, p.created_at FROM projects p
JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
ORDER BY p.created_at DESC, p.id DESC
LIMIT $2 OFFSET $3
`

type ListProjectsByUserParams struct {
	UserID string
	Limit  int32
	Offset int32
}

func (q *Queries) ListProjectsByUser(ctx context.Context, arg ListProjectsByUserParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
