// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_users (project_id, user_id, role) VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID string
	UserID    string
	Role      string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, created_at FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role FROM project_users WHERE project_id = $1 AND user_id = $2 LIMIT 1
`

type GetProjectMemberParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectUser, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectUser
	err := row.Scan(&i.ProjectID, &i.UserID, &i.Role)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id, u.email, u.name, u.created_at FROM users u
JOIN project_users pu ON pu.user_id = u.id
WHERE pu.project_id = $1
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT p.id, p.name, p.created_at FROM projects p
JOIN project_users pu ON pu.project_id = p.id
WHERE pu.user_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
