// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxes.sql

package db

import (
	"context"
)

const countRunningSandboxesByProject = `-- name: CountRunningSandboxesByProject :one
SELECT COUNT(*) FROM sandboxes WHERE project_id = $1 AND stopped_at IS NULL
`

func (q *Queries) CountRunningSandboxesByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningSandboxesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunningSandboxesByUser = `-- name: CountRunningSandboxesByUser :one
SELECT COUNT(*) FROM sandboxes WHERE user_id = $1 AND stopped_at IS NULL
`

func (q *Queries) CountRunningSandboxesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningSandboxesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSandboxesByProject = `-- name: CountSandboxesByProject :one
SELECT COUNT(*) FROM sandboxes WHERE project_id = $1
`

func (q *Queries) CountSandboxesByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSandboxesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (project_id, user_id, name) VALUES ($1, $2, $3) RETURNING id, project_id, user_id, created_at, stopped_at, name
`

type CreateSandboxParams struct {
	ProjectID string
	UserID    string
	Name      string
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, createSandbox, arg.ProjectID, arg.UserID, arg.Name)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.StoppedAt,
		&i.Name,
	)
	return i, err
}

const getSandboxByIDAndUser = `-- name: GetSandboxByIDAndUser :one
SELECT s.id, s.project_id, s.user_id, s.created_at, s.stopped_at, s.name FROM sandboxes s
JOIN project_users pu ON pu.project_id = s.project_id
WHERE s.id = $1 AND pu.user_id = $2
`

type GetSandboxByIDAndUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetSandboxByIDAndUser(ctx context.Context, arg GetSandboxByIDAndUserParams) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, getSandboxByIDAndUser, arg.ID, arg.UserID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.StoppedAt,
		&i.Name,
	)
	return i, err
}

const listSandboxesByProject = `-- name: ListSandboxesByProject :many
SELECT id, project_id, user_id, created_at, stopped_at, name FROM sandboxes WHERE project_id = $1 ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSandboxesByProjectParams struct {
	ProjectID string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListSandboxesByProject(ctx context.Context, arg ListSandboxesByProjectParams) ([]Sandbox, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sandbox
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.CreatedAt,
			&i.StoppedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restartSandbox = `-- name: RestartSandbox :one
UPDATE sandboxes s SET stopped_at = NULL
FROM project_users pu
WHERE s.id = $1 AND s.stopped_at IS NOT NULL
  AND pu.project_id = s.project_id AND pu.user_id = $2
RETURNING s.id, s.project_id, s.user_id, s.created_at, s.stopped_at, s.name
`

type RestartSandboxParams struct {
	ID     string
	UserID string
}

func (q *Queries) RestartSandbox(ctx context.Context, arg RestartSandboxParams) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, restartSandbox, arg.ID, arg.UserID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
		&i.StoppedAt,
		&i.Name,
	)
	return i, err
}

const stopSandbox = `-- name: StopSandbox :execrows
UPDATE sandboxes s SET stopped_at = now()
FROM project_users pu
WHERE s.id = $1 AND pu.project_id = s.project_id AND pu.user_id = $2
  AND s.stopped_at IS NULL
`

type StopSandboxParams struct {
	ID     string
	UserID string
}

func (q *Queries) StopSandbox(ctx context.Context, arg StopSandboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, stopSandbox, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
