// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxes.sql

package db

import (
	"context"
)

const countSandboxesByProject = `-- name: CountSandboxesByProject :one
SELECT COUNT(*) FROM sandboxes WHERE project_id = $1
`

func (q *Queries) CountSandboxesByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSandboxesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (project_id, user_id) VALUES ($1, $2) RETURNING id, project_id, user_id, status, created_at, stopped_at, version
`

type CreateSandboxParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, createSandbox, arg.ProjectID, arg.UserID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.StoppedAt,
		&i.Version,
	)
	return i, err
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, project_id, user_id, status, created_at, stopped_at, version FROM sandboxes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id string) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.StoppedAt,
		&i.Version,
	)
	return i, err
}

const listSandboxesByProject = `-- name: ListSandboxesByProject :many
SELECT id, project_id, user_id, status, created_at, stopped_at, version FROM sandboxes WHERE project_id = $1 ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSandboxesByProjectParams struct {
	ProjectID string
	Limit     int32
	Offset    int32
}

func (q *Queries) ListSandboxesByProject(ctx context.Context, arg ListSandboxesByProjectParams) ([]Sandbox, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxesByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sandbox
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.StoppedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSandboxStatus = `-- name: UpdateSandboxStatus :execrows
UPDATE sandboxes SET status = $2, stopped_at = now(), version = version + 1 WHERE id = $1 AND version = $3
`

type UpdateSandboxStatusParams struct {
	ID      string
	Status  string
	Version int32
}

func (q *Queries) UpdateSandboxStatus(ctx context.Context, arg UpdateSandboxStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSandboxStatus, arg.ID, arg.Status, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
