// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, created_at, oauth_sub, plan_id FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.OauthSub,
		&i.PlanID,
	)
	return i, err
}

const getUserByOAuthSub = `-- name: GetUserByOAuthSub :one
SELECT id, email, name, created_at, oauth_sub, plan_id FROM users WHERE oauth_sub = $1 LIMIT 1
`

func (q *Queries) GetUserByOAuthSub(ctx context.Context, oauthSub string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOAuthSub, oauthSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.OauthSub,
		&i.PlanID,
	)
	return i, err
}

const upsertUserByOAuthSub = `-- name: UpsertUserByOAuthSub :one
INSERT INTO users (oauth_sub, email, name) VALUES ($1, $2, $3)
ON CONFLICT (oauth_sub) DO UPDATE SET oauth_sub = users.oauth_sub
RETURNING id, email, name, created_at, oauth_sub, plan_id
`

type UpsertUserByOAuthSubParams struct {
	OauthSub string
	Email    string
	Name     string
}

func (q *Queries) UpsertUserByOAuthSub(ctx context.Context, arg UpsertUserByOAuthSubParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByOAuthSub, arg.OauthSub, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.OauthSub,
		&i.PlanID,
	)
	return i, err
}
